### ISSUE TITLE
NameError: name 'main' is not defined

### ISSUE THREAD

**Issue by khawar-islam** [facebookresearch/noisy_few_shot#3]
Dear @kevinjliang ,

Is this code working? I am simply running an outlier file but it says 'main' is not defined

**Traceback**
```
(nfsl) cvpr@cvprlab:/media/cvpr/CM_22/noisy_few_shot$ python3 create_miniimagenet_outliers.py
Traceback (most recent call last):
  File "/media/cvpr/CM_22/noisy_few_shot/create_miniimagenet_outliers.py", line 1806, in <module>
    main()
NameError: name 'main' is not defined
```

**Comment by kevinjliang** [comment]
My apologies. I originally generated the outlier data from an IPython notebook and made a couple errors while translating it over to a python script. I’ve made fixes [here](https://github.com/facebookresearch/noisy_few_shot/commit/ba2018aa7499bb910aab2f04c120608ec50c287a). 

Note that the `--imagenet_dir` arg should be pointed to the training split of full-size ImageNet.

**Comment by khawar-islam** [comment]
Thank you. If i run the `main.py` file it gives an `error : error: the following arguments are required: --name`. **What does it mean?** I have checked in the `main.py` argument, there are no choices and I have no idea what should I pass in `--name ` argument.

**Comment by khawar-islam** [comment]
@kevinjliang I have copied miniimagnet folder inside the data folder and tried to run `bash/train_backbone` file. It gives an error 
I think there is some problem to connect with dropbox

I manually downloaded three models from dropbox and copied inside data/miniimagenet folder

```
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb2733f11f0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by kevinjliang** [comment]
I haven't seen this before. Assuming it's a dropbox issue: MiniImageNet is quite small, and the MiniImageNet class comes with a [download option](https://github.com/facebookresearch/noisy_few_shot/blob/main/mini_imagenet.py#L78) at initialization. Can you give that a try? Once it downloads, make sure it's in the right location in your directory (`./data`).

**Comment by khawar-islam** [comment]
Hello @kevinjliang Thank you I solved the problem before running the code we have to first run the `visdom` then we have to start training.
