### ISSUE TITLE
dataset and training process

### ISSUE THREAD

**Issue by goodboyyahou** [facebookresearch/noisy_few_shot#5]
Hello, I cannot download the data in miniimagenet.py due to network reasons, so I would like to ask you about the specific organization form of the data and how to deal with the data set downloaded by myself. Secondly, I cannot complete the training for many reasons, so I hope to ask you again to verify the complete training process.

**Comment by kevinjliang** [comment]
Hi, sorry to hear that. The data for this code base is downloaded in a pickle format that's fairly standard for few-shot learning. If you're having trouble with the download, perhaps you could look at the [mini-imagenet-tools repo](https://github.com/yaoyao-liu/mini-imagenet-tools) as a reference. Essentially you need to format the image data and labels into a pytorch Dataset, as specified [here](https://github.com/facebookresearch/noisy_few_shot/blob/main/mini_imagenet.py#L117-L124). You'll need to sort out any issues with data before being able to successfully train the model.
