### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kailugaji** [facebookresearch/noisy_few_shot#6]
Hello, if I want to verify tieredimagenet data set, can I ask you about the download address of the pkl form data set and how to define its Outlier noise?

**Comment by kevinjliang** [comment]
The TieredImageNet dataset format used in this repo is a fairly standard one. Try using [this class](https://github.com/learnables/learn2learn/blob/master/learn2learn/vision/datasets/tiered_imagenet.py), which includes code for automatically downloading.

The outlier noise data in our experiments is defined [here](https://github.com/facebookresearch/noisy_few_shot/blob/main/create_miniimagenet_outliers.py). It's the same for both MiniImageNet and TieredImageNet; the outlier classes are defined as the ImageNet classes not used by both MiniImageNet and TieredImageNet.

**Comment by kailugaji** [comment]
Thank you very much for your reply, it is very helpful to me. I wish you a happy life and a smooth work.
