### ISSUE TITLE
question about  ”warmup_scheduler“

### ISSUE THREAD

**Issue by wait1ng** [facebookresearch/noisy_few_shot#7]
Hello, I would like to know about line 23 in the main.py file about "from warmup_scheduler import GradualWarmupScheduler", is "warmup_scheduler" a customized module?sorry i I didn't find this module, when I try to run main.py, it throws the following exception. I want to know the function about this module and where it is located? Thank you and have a good day at work.
Traceback (most recent call last):
  File "D:/MyPython/noisy_few_shot-main/main.py", line 23, in <module>
    from warmup_scheduler import GradualWarmupScheduler
ModuleNotFoundError: No module named 'warmup_scheduler'

**Comment by kevinjliang** [comment]
`warmup_scheduler` can be found here: https://pypi.org/project/warmup-scheduler/

If you follow the [setup instructions](https://github.com/facebookresearch/noisy_few_shot/blob/main/environment.yml), it should be installed automatically; it's in the [env file](https://github.com/facebookresearch/noisy_few_shot/blob/main/environment.yml).
